### ISSUE TITLE
Public method for getting all tables for a dataset

### ISSUE THREAD

**Issue by ruxandraburtica** [tylertreat/BigQuery-Python#97] opened 2016-05-16 10:31 UTC
## Need

Currently, there's no support for getting all tables from a given dataset (there is `_get_all_tables`, but it skips tables that do not respect a certain format).

## Solution

Add `get_all_tables(dataset_id)` to the `BigQueryClient` class.

**Comment by jaamiller** [comment] 2016-05-16 10:57
I'd second this proposal. There is a need for
get_all_tables(dataset_id)

The _get_all_tables is misnamed, since as ruxandraburtica pointed out, it excludes tables that do not follow a specific format that includes a date and an appID.

Additionally, the _get_all_tables method does not support the common format for daily tables, as used by e.g. Google Analytics exports to BQ.
The format for these date-ranged tables is as follows:
ga_sessions_20150430

the _get_all_tables method should return a date object (?) and the table prefix, allowing the date ranges to be queried as intended.

**Comment by tylertreat** [comment] 2016-05-17 00:48
Addressed in #98.

**Closed by tylertreat** 2016-05-17 00:48 UTC
